# Generated by Django 4.2.29 on 2026-04-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_ephemeral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleetping',
            options={'default_permissions': (), 'verbose_name': 'Fleet Ping', 'verbose_name_plural': 'Fleet Pings'},
        ),
    ]
